baseurl = "https://allanchain.github.io/blog"
languageCode = "en-us"
title = "AC's Blog"
theme = "hugo-xmag-solarized"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
paginate = 6
rssLimit = 20
preserveTaxonomyNames = true
hasCJKLanguage = true
canonifyURLs = false
enableEmoji = true
disablePathToLower = true
enableGitInfo = false

[permalinks]
    programing = "/programing/:year/:slug/"
    cheatsheets = "/cheatsheets/:slug"
    academy = "/academy/:year/:slug/"

[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    style = "solarized-dark"
    lineNos = true
