packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  "@release-it/conventional-changelog@*":
    dependencies:
      "semver": "*"

yarnPath: .yarn/releases/yarn.cjs
