packageExtensions:
  "@release-it/conventional-changelog@*":
    dependencies:
      semver: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"

yarnPath: .yarn/releases/yarn-3.2.0-rc.12.cjs
