type Image {
  src: String,
  lazySrc: String
}

type Post implements Node {
  id: ID!,
  title: String!,
  createdAt: Date!,
  lastEditedAt: Date!,
  slug: String!,
  summary: String,
  image: Image, # Post head image
  logo: Image,  # logo from preferred label
  labels: [Label],
  body: String!,
  serializedHeadings: String!
}

type Label implements Node {
  id: ID!,
  description: String,
  logo: Image,
  name: String!,
  type: String!,
  color: String!
}
