baseurl = "https://allanchain.github.io/blog/"
languageCode = "en-us"
title = "AC's Blog"
theme = "hugo-xmag-solarized"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
paginate = 6
preserveTaxonomyNames = true
hasCJKLanguage = true
canonifyURLs = true
enableEmoji = true
disablePathToLower = true
enableGitInfo = true

[permalinks]
    programing = "/programing/:year/:slug/"
    academy = "/academy/:year/:slug/"

[markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 200
    github_edit = "https://github.com/AllanChain/blog/edit/master/content/"
    footer = "&copy; 2019 Allan Chain<br>Powered by hugo and hugo-xmag theme"
    favicon = "//allanchain.github.io/img/favicon.ico"

[params.text]
    back = "&larr; Home"
    edit = "Edit &rarr;"
    truncated = "&hellip;"

[params.gitalk]
  enabled = true
  clientID = "ec59190f01750575678c"
  clientSecret = "878d20cc97cca9a90ac67fb51dcd0dcbfb27699b"
  repo = "blog"
  owner = "AllanChain"
  admin = ["AllanChain"]

[params.termThumbnails]
  python = "https://www.python.org/static/img/python-logo-large.c36dccadd999.png"
