baseurl = "https://allanchain.github.io/blog/"
languageCode = "en-us"
title = "AC's Blog"
theme = "hugo-xmag-solarized"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
canonifyURLs = true
paginate = 6
disablePathToLower = true

[permalinks]
    programing = "/programing/:year/:slug/"
    academy = "/academy/:year/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 200
    github_edit = "https://github.com/AllanChain/blog/edit/master/content/"
    footer = "&copy; 2019 Allan Chain\nPowered by hugo and hugo-xmag theme"
    favicon = "//allanchain.github.io/img/favicon.ico"

[params.text]
    back = "&larr; Home"
    edit = "Edit &rarr;"
    truncated = "&hellip;"
