on:
  push:
    branches:
      - gridsome

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@gridsome
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v1
      with:
        path: node_modules
        id: cache
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-
    - name: Install Packages
      run: npm install
    - name: Build App
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
