query(
  $repo: String!
  $owner: String!
  $postNumber: Int!
  $commentCount: Int!
  $reactionCount: Int!
) {
  repository(name: $repo, owner: $owner) {
    issue(number: $postNumber) {
      reactions(first: $reactionCount) {
        nodes {
          content
          user {
            login
          }
        }
      }
      comments(first: $commentCount) {
        nodes {
          id
          resourcePath
          author {
            avatarUrl(size: 64)
            login
          }
          bodyHTML
          createdAt
          reactions(first: $reactionCount) {
            nodes {
              content
              user {
                login
              }
            }
          }
        }
      }
    }
  }
}
