on:
  push:
    branches:
      - gridsome
  issues:
    types: [opened, edited]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # if: ${{ contains(github.event.issue.labels.*.name, 'blog') }}
    steps:
    - uses: hmarr/debug-action@master
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-
    - name: Install Packages
      run: npm install
    - name: Build App
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./blog
        publish_branch: gh-pages
