name: Build and Deploy to gh-pages

on:
  push:
    tags:
      - v*
  issues:
    types: [opened, edited]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: > 
      (contains(github.event.issue.labels.*.name, '@post') &&
      github.event.sender.login == 'AllanChain') ||
      github.event.pusher.name == 'AllanChain'
    steps:
    - uses: actions/checkout@master
    - name: debug
      run: cat "$GITHUB_EVENT_PATH" | jq -M .
      env:
        A: ${{ contains(github.event.issue.labels.*.name, '@post') }}
        B: ${{ github.event.sender.login == 'AllanChain' }}
        C: ${{ github.event.pusher.name == 'AllanChain' }}
        D: ${{ (false && true) || false }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Prepare Content to Hash (ignore app version)
      run: tail -n +4 package-lock.json > .content.to.hash
    - uses: actions/cache@v2
      with:
        path: mode_modules
        key: node-${{ hashFiles('.content.to.hash') }}
        restore-keys: |
          node-
    - name: Install Packages
      run: npm install
    - name: Build App
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./blog
        publish_branch: gh-pages
