on:
  push:
    branches:
      - gridsome
  issues:
    types: [opened, edited]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@master
    - name: debug
      run: |
        echo "$D1"
        echo "$D2"
        echo "$D3"
        echo "$D4"
      env:
        D1: ${{ contains(github.event.issue.labels.*.name, 'blog') }}
        D2: ${{ github.event.pusher.name }}
        D3: ${{ github.event.pusher.name == 'AllanChain' }}
        D4: ${{ contains(github.event.pusher.name, 'AllanChain') }}
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-
    - name: Install Packages
      run: npm install
    - name: Build App
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./blog
        publish_branch: gh-pages
