name: Move Issue to Project Board

on:
  issues:
    types: [labeled]

jobs:
  blog-code:
    runs-on: ubuntu-latest
    if: contains(fromJson('["bug", "enhancement"]'), github.event.label.name)
    steps:
      - uses: alex-page/github-project-automation-plus@v0.6.0
        with:
          project: Blog bugs & todos
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  wip-blog-post:
    runs-on: ubuntu-latest
    if: github.event.label.name == '@WIP'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.6.0
        with:
          project: Post Process
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  done-blog-post:
    runs-on: ubuntu-latest
    if: github.event.label.name == '@post'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.6.0
        with:
          project: Post Process
          column: Done
          repo-token: ${{ secrets.GITHUB_TOKEN }}
