name: Move Issue to Project Board

on:
  issues:
    types: [labeled]

jobs:
  blog-code:
    runs-on: ubuntu-latest
    if: contains(fromJson('["bug", "enhancement"]'), github.event.label.name)
    steps:
      - name: Add issue to project board
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.projects.createCard({
              column_id: 9842002,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
  blog-post:
    runs-on: ubuntu-latest
    if: github.event.label.name == '@WIP'
    steps:
      - name: Add issue to project board
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.projects.createCard({
              column_id: 10075483,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
